language: php
sudo: false

php:
  - 7.3
  - 7.4

matrix:
    include:
        - php: 7.3
          env: dependencies=lowest

before_script:
  - composer install --no-interaction -o
  - if [ "$dependencies" = "lowest" ]; then composer update -o --prefer-lowest; fi;

script:
  - mkdir -p build/logs
  - bin/phpunit

after_script:
  - bin/coveralls -v
